### ISSUE TITLE
Cannot mount mobs on crate object

### ISSUE THREAD

**Issue by winsrp** [elytra/archimedes-ships-plus#43]
I only have this mod on, for single player, I make the ship with crate plates in it, mount a mob, assemble the ship, all fine until then, but when I click the mount ship button, or I click the help to start driving, the mob just falls into the ground ignoring the ship.

**Comment by darkevilmac** [comment]
Crates are super buggy, I've been looking at them for a while now and I think the only reasonable way to fix the things is a rewrite. Leaving open so I don't forget.

**Comment by JCMais** [comment]
@darkevilmac how about modify the block so the block is like a real cage, and the entity is not above it, but stored somewhere else (idk if this is possible in minecraft)?

Take this as example:
http://i.imgur.com/ro2Q3oa.png

Red block is the crate block, small animals can only be stored in the single crate block, big animals must be put in the two blocks crate.

**Comment by rdunham3** [comment]
I've been meaning to get in here to open an issue about buggy critter crates for the longest time and keep getting sidetracked.  Here goes.

As stated above the critters tend to fall through.  How about a static render of the critter's shape appearing on top the crate (no animations etc.) so it's not trying to run any AI or world interaction code on it as the ship does its thing?  

For larger creatures, shrink the model so it fits on top the single block.  I'm assuming there's code in Minecraft to scale a model...if not, disregard that part of the suggestion.

**Comment by darkevilmac** [comment]
> I've been meaning to get in here to open an issue about buggy critter crates for the longest time and keep getting sidetracked. Here goes.
> 
> As stated above the critters tend to fall through. How about a static render of the critter's shape appearing on top the crate (no animations etc.) so it's not trying to run any AI or world interaction code on it as the ship does its thing?
> 
> For larger creatures, shrink the model so it fits on top the single block. I'm assuming there's code in Minecraft to scale a model...if not, disregard that part of the suggestion.

More effort than required, I just need to make it so when the mob hits or lands on the crate they're tethered to it with the entity id, then every tick set their position to the crate position.

**Comment by JCMais** [comment]
Now I'm curious, if it's not done currently that way, how it's implemented?

**Comment by darkevilmac** [comment]
> then every tick set their position to the crate position.
> Now I'm curious, if it's not done currently that way, how it's implemented?

This is how it is supposed to work unfortunately it wasn't implemented properly and the code is quite a mess so the best choice to fix it at this point is a rewrite.

**Comment by darkevilmac** [comment]
Tried fixing it, completely untested so please give them a try on the 1.8.9 builds and let me know if it works. (Backup stuff first!)

**Comment by winsrp** [comment]
dumb question, how do it test it? is there somewhere I can download it?

**Comment by midniteoftherose** [comment]
will test this in vid for ya mac

**Comment by midniteoftherose** [comment]
i just realized i have no clue how to use crates haha

**Comment by midniteoftherose** [comment]
[i cant use crates :( ](http://plays.tv/video/56df1b19136b52c279)

**Comment by winsrp** [comment]
lol.... it hink you have a ship (not assembled) put a cow on top of a crate, and then assemble?

**Comment by midniteoftherose** [comment]
nah didnt work

**Comment by winsrp** [comment]
I've seen several items that transport mobs, with mob nets and what not... I think the easiest way for this to work is that when you assemble the shit, and there is a crate and there is mob on top of it, check the type of mob and create a custom mob storage that looks like a spawner, or just a box with a picture of the mob type on top of it, or the picture of the mob egg, whatever, so all mobs get converted to their respective storages one per crate on the ship, and when you move, you just move another block; when you disassemble the crates go back to the original small type, and the mobs get re-placed in the world.

**Comment by JCMais** [comment]
Two observations:

1. You should lead the mob to the create while the ship is not assembled.
2. You should not disassemble the ship while near other blocks, otherwise its going to grab those blocks when you assemble it again, or just fail to disassemble.

**Comment by midniteoftherose** [comment]
thats the problem, i want to be able to assemble it in a survival campaign

**Comment by darkevilmac** [comment]
Fixed in 1.8.9 and 1.9.
