### ISSUE TITLE
[AS 1.8.9 INDEV D] [MW 1.8.9 INDEV E] Sections of Ship Vanishing

### ISSUE THREAD

**Issue by Ancientcrafter** [elytra/archimedes-ships-plus#79]
Constructed ship out of Nether Quartz Blocks, Stairs, ETC. and White Air balloons. Assembled mounted and moved with no difficulty. I was attempting to make my ship into a mobile base by adding a furnace Tinkers Construct Workstation, Enchanting Table and Crystal Chests for storage. Loaded up the chests with various items (vanilla food and some other assorted tools) and assembled the ship just fine. When I attempted to mount the ship however I dropped out of the ship and half the ship just vanished completely. There were no ghost entities, invisible blocks, or anything else. Just half the ship was warped into oblivion. Any blocks that had inventories also purged their inventories as well. Previously attempted the mobile base idea with the 1.8 version a Better Storage Mod (http://mods.curse.com/mc-mods/minecraft/233225-ezstorage) computer system on board and ran into the same issue.

Modpack:
The Essentials (V 1.8.9)
by Sblectric

Error Pastebin Link:
http://pastebin.com/N1nnpfsh

**Comment by darkevilmac** [comment]
Mod version number, if you can post that error log to hastebin that would
be great as in currently on mobile and pastebin isn't rendering properly.

**Comment by DanTheColoradan** [comment]
Copied pastebin to hastebin: http://hastebin.com/uwekolixef.css

Let me know if that link doesn't work. Haven't used hastebin before.

**Comment by darkevilmac** [comment]
@MrRiegel Seems to be related to your AbstractBlock class in Furnus, caused by your breakBlock method. Only option would be checking if your tile is null, and if it isn't continue normally if it's not then just call the super method.

**Comment by MrRiegel** [comment]
fixed
